GET http://localhost:7000/about

###

GET http://localhost:7000/

###

GET http://localhost:7000/tickets

###

GET http://localhost:7000/animals

###

GET http://localhost:7000/animals/1

###

GET http://localhost:7000/animals/6

###

POST http://localhost:7000/animals
Content-Type: application/json

{
  "name": "Marmot",
  "count": 20
}

###

DELETE http://localhost:7000/animals/4


###

PATCH http://localhost:7000/animals/1
Content-Type: application/json

{
  "name": "Beaver",
  "count": 50
}